### ISSUE TITLE
data/example_ioevents.csv is missing

### ISSUE THREAD

**Issue by rmuch** [MIT-LCP/mimic-workshop#2]
In `01-example-patient-heart-failure.ipynb`, for the example **Plot 5: intravenous medications**, the file `data/example_ioevents.csv` is missing. This makes it impossible to run the sample.

**Comment by tompollard** [comment]
Thanks for the fix @rmuch (and thanks for joining us at the workshop!)

Tom

**Comment by rajendraranabhat** [comment]
Where can i download the example_ioevents.csv file? Also other csv file like example_labevents.csv etc. Is example_ioevents.csv corresponds INPUTEVENTS_CV_DATA_TABLE.csv.gz or INPUTEVENTS_MV_DATA_TABLE.csv.gz in MIMIC-III database?

**Comment by tompollard** [comment]
Some of the IPython Notebook files may refer to csv files, but these are no longer part of the workshop repository. Instead the data is provided in the sqlite file. For instructions on how to install the sample dataset, see the readme: https://github.com/MIT-LCP/mimic-workshop/blob/master/README.md

Note that the IOEVENTS table was replaced with three separate tables in version 1.2 of MIMIC-III: INPUTEVENTS_MV, INPUTEVENTS_CV and OUTPUTEVENTS. Please refer to the MIMIC documentation for further information: http://mimic.physionet.org/about/releasenotes/

We intend to develop the content in this repository over time, and we encourage you to make contributions and to submit updates via pull requests.
