### ISSUE TITLE
Connection to DB instance fails. 

### ISSUE THREAD

**Issue by kjaugustin** [MIT-LCP/mimic-workshop#5]
connection to db host mimic3-1.coh8b3jmul4y.us-west-2.rds.amazonaws.com fails. mlcc_mortality_prediction.ipynb attempts to connect to the above mentioned DB instance and the connection fails.

**Comment by tompollard** [comment]
@kjaugustin the contents of this folder are used for workshops hosted by the lab, and the AWS instance is not publicly available. We will remove the hostname from files where it is mentioned.
